# Generated by Django 5.0.6 on 2025-03-28 21:22

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(choices=[('Music', 'Music'), ('Sports', 'Sports'), ('Tech', 'Tech'), ('Art', 'Art'), ('Food', 'Food'), ('Comedy', 'Comedy')], max_length=100)),
                ('duration', models.DurationField(blank=True, default=datetime.timedelta(0), null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('site', models.URLField(blank=True)),
                ('venue', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artist', models.CharField(max_length=100)),
                ('artist_short_description', models.TextField(blank=True)),
                ('why_attend', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('image_artist', models.ImageField(blank=True, null=True, upload_to='artist_images/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
