# Generated by Django 5.0.6 on 2025-03-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsz',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='eventsz',
            name='created_by',
        ),
    ]
