# Generated by Django 5.0.6 on 2025-03-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='rsvp',
            name='user',
        ),
    ]
