# Generated by Django 5.0.6 on 2025-03-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_rsvp_user_alter_rsvp_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('Attending', 'Attending'), ('Not_Attending', 'Not Attending'), ('MAYBE', 'Maybe'), ('NULL', 'null')], default='NULL', max_length=20),
        ),
    ]
