# Generated by Django 5.0.6 on 2025-03-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_alter_rsvp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('Attending', 'Attending'), ('Not_Attending', 'Not Attending'), ('MAYBE', 'Maybe')], default='Not_Attending', max_length=20),
        ),
    ]
