# Generated by Django 5.0.6 on 2025-03-24 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('site', models.URLField(blank=True)),
                ('venue', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artist', models.CharField(max_length=100)),
                ('artist_short_description', models.TextField(blank=True)),
                ('why_attend', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('similar_events', models.ManyToManyField(blank=True, to='accounts.event')),
            ],
        ),
    ]
