# Generated by Django 5.0.6 on 2025-03-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_events_delete_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='duration',
            field=models.DurationField(default='00:00:00'),
        ),
    ]
