# Generated by Django 5.0.6 on 2025-03-24 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_events_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
