# Generated by Django 5.0.6 on 2025-03-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_events_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
