# Generated by Django 5.0.6 on 2025-04-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='event',
        ),
    ]
